import { useState, useEffect } from 'react';
import { HiArrowRight, HiCheck, HiStar, HiLightningBolt, HiMenuAlt3, HiX, HiTrendingUp, HiSparkles, HiLockClosed, HiClock, HiPlay } from 'react-icons/hi';
import FooterSunMascot from './FooterSunMascot';
import Forum from './Forum';

// Import photorealistic human images generated by AI
import teacherMathImg from '../assets/teacher_math.png';
import studentLearningImg from '../assets/student_learning.png';
import educatorsTeamImg from '../assets/educators_team.png';
import studentSuccessImg from '../assets/student_success.png';

const SUBJECTS = [
  {
    id: 'toan',
    label: 'Toán Học',
    desc: 'Đại số, Hình học, Giải tích và các dạng bài thi THPTQG',
    count: '120+ đề',
    bg: '#4F46E5',
    emoji: '🦉',
    combos: ['A01', 'B00', 'D01'],
  },
  {
    id: 'ly',
    label: 'Vật Lý',
    desc: 'Dao động, Sóng, Điện từ — bám sát cấu trúc đề thi mới',
    count: '100+ đề',
    bg: '#F97316',
    emoji: '🦊',
    combos: ['A01'],
  },
  {
    id: 'anh',
    label: 'Tiếng Anh',
    desc: 'Ngữ pháp, Đọc hiểu, Từ vựng trọng tâm THPTQG 2026',
    count: '100+ đề',
    bg: '#10B981',
    emoji: '🐸',
    combos: ['A01', 'D01'],
  },
  {
    id: 'hoa',
    label: 'Hóa Học',
    desc: 'Hữu cơ, Vô cơ, Bài toán tính toán hóa học nâng cao',
    count: '90+ đề',
    bg: '#EF4444',
    emoji: '🐙',
    combos: ['B00'],
  },
  {
    id: 'sinh',
    label: 'Sinh Học',
    desc: 'Di truyền, Tiến hóa, Sinh thái — ôn thi khối B chuyên sâu',
    count: '80+ đề',
    bg: '#8B5CF6',
    emoji: '🐢',
    combos: ['B00'],
    isFree: true,
  },
  {
    id: 'van',
    label: 'Ngữ Văn',
    desc: 'Nghị luận, Đọc hiểu, Phân tích tác phẩm văn học 12',
    count: '70+ đề',
    bg: '#F59E0B',
    emoji: '🦋',
    combos: ['D01'],
  },
];

const STATS = [
  { icon: '🏆', value: '5 năm', label: 'hoạt động' },
  { icon: '👨‍🏫', value: '100%', label: 'giáo viên 8.0+ điểm' },
  { icon: '👩‍🎓', value: '42,500+', label: 'học sinh đã đồng hành' },
  { icon: '🎯', value: '90%', label: 'đạt mục tiêu điểm' },
];

const FEATURES = [
  { icon: '🔍', title: 'Chẩn đoán lỗ hổng tức thì', desc: 'AI phân tích kết quả và chỉ ra đúng kiến thức bạn đang yếu sau mỗi bài làm.' },
  { icon: '🗺️', title: 'Lộ trình học cá nhân hóa', desc: 'Không học dàn trải. Bản đồ học tập tự cập nhật theo điểm yếu của bạn mỗi ngày.' },
  { icon: '📝', title: 'Sinh đề sửa sai chuyên biệt', desc: 'AI tạo bộ câu hỏi tập trung đúng dạng bài bạn sai để luyện tập khắc phục ngay.' },
  { icon: '📊', title: 'Theo dõi tiến độ trực quan', desc: 'Biểu đồ điểm số theo tuần, streak học tập, dự đoán điểm THPTQG theo phong độ thực tế.' },
];

const getSpikePath = () => {
  const points = [];
  const numSpikes = 36;
  const cx = 300;
  const cy = 300;
  const rMin = 210;
  const rMax = 238;
  for (let i = 0; i < numSpikes; i++) {
    const angle1 = (i * 2 * Math.PI) / numSpikes;
    const angle2 = ((i + 0.5) * 2 * Math.PI) / numSpikes;
    points.push(`${(cx + rMax * Math.cos(angle1)).toFixed(1)},${(cy + rMax * Math.sin(angle1)).toFixed(1)}`);
    points.push(`${(cx + rMin * Math.cos(angle2)).toFixed(1)},${(cy + rMin * Math.sin(angle2)).toFixed(1)}`);
  }
  return `M ${points.join(' L ')} Z`;
};
const spikePath = getSpikePath();

const MOCK_LEADERBOARD = [
  { rank: 1, name: "Nguyễn Lâm Vy", combo: "A01 (Toán - Lý - Anh)", target: "28.5", actual: "28.2", streak: 42, badge: "Thủ khoa Lý 12", avatar: "LV" },
  { rank: 2, name: "Trần Minh Đức", combo: "B00 (Toán - Hóa - Sinh)", target: "29.0", actual: "28.4", streak: 35, badge: "Thần tốc Hóa Học", avatar: "MĐ" },
  { rank: 3, name: "Lê Quỳnh Chi", combo: "D01 (Toán - Văn - Anh)", target: "27.5", actual: "27.1", streak: 28, badge: "Đệ nhất Anh ngữ", avatar: "QC" },
  { rank: 4, name: "Phạm Minh Hoàng", combo: "A01 (Toán - Lý - Anh)", target: "28.0", actual: "26.9", streak: 21, badge: "Chiến thần Toán Học", avatar: "MH" },
  { rank: 5, name: "Đỗ Gia Bảo", combo: "B00 (Toán - Hóa - Sinh)", target: "27.8", actual: "26.5", streak: 17, badge: "Chuyên gia Sinh học", avatar: "GB" }
];

const FEATURED_COURSES = [
  {
    id: 1,
    title: "Ứng dụng đạo hàm khảo sát đồ thị hàm số",
    subject: "Toán học",
    price: "499.000",
    teacherName: "Thầy Thế Anh",
    duration: "32 giờ học • 45 bài giảng",
    rating: "4.8",
    students: "2,150",
    imageBg: "linear-gradient(135deg, #0984E3, #74b9ff)",
    lessons: [
      { name: "Bài 1: Sự đồng biến, nghịch biến của hàm số", duration: "18:45", isFree: true },
      { name: "Bài 2: Cực trị của hàm số và kỹ thuật bấm máy Casio", duration: "25:30", isFree: true },
      { name: "Bài 3: Giá trị lớn nhất, nhỏ nhất trên đoạn", duration: "22:15", isFree: false },
      { name: "Bài 4: Khảo sát sự biến thiên và vẽ đồ thị nâng cao", duration: "32:10", isFree: false }
    ]
  },
  {
    id: 2,
    title: "Chinh phục toàn diện Dao động cơ & Sóng cơ học",
    subject: "Vật lý",
    price: "599.000",
    teacherName: "Cô Thu Hương",
    duration: "40 giờ học • 55 bài giảng",
    rating: "4.9",
    students: "1,890",
    imageBg: "linear-gradient(135deg, #e17055, #fab1a0)",
    lessons: [
      { name: "Bài 1: Khái niệm Dao động điều hòa và các phương trình cốt lõi", duration: "20:15", isFree: true },
      { name: "Bài 2: Con lắc lò xo và bài toán năng lượng", duration: "26:40", isFree: false },
      { name: "Bài 3: Con lắc đơn và sự biến thiên chu kỳ", duration: "18:30", isFree: false }
    ]
  },
  {
    id: 3,
    title: "Ngữ pháp Tiếng Anh trọng tâm thi THPTQG 2026",
    subject: "Tiếng Anh",
    price: "399.000",
    teacherName: "Cô Quỳnh Chi",
    duration: "28 giờ học • 38 bài giảng",
    rating: "4.7",
    students: "950",
    imageBg: "linear-gradient(135deg, #00b894, #55efc4)",
    lessons: [
      { name: "Bài 1: Trọn bộ 12 thì trong Tiếng Anh và dấu hiệu nhận biết", duration: "15:45", isFree: true },
      { name: "Bài 2: Câu bị động và các dạng đặc biệt thường gặp", duration: "22:20", isFree: false },
      { name: "Bài 3: Câu điều kiện và Mệnh đề giả định", duration: "20:10", isFree: false }
    ]
  }
];

export default function LandingPage({ 
  currentUser, 
  onNavigateToAuth, 
  onBackToDashboard, 
  onLogout,
  forumPosts = [],
  onAddPost,
  onLikePost,
  onAddComment
}) {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [profileDropdownOpen, setProfileDropdownOpen] = useState(false);
  const [activeLandingView, setActiveLandingView] = useState('home'); // 'home' | 'subjects' | 'features' | 'about' | 'pricing'
  const [leaderboardTab, setLeaderboardTab] = useState('score'); // 'score' or 'streak'
  const [selectedPreviewCourse, setSelectedPreviewCourse] = useState(null);

  const handleAddPostPublic = (newPost) => {
    if (!currentUser) {
      alert("Vui lòng đăng nhập hoặc đăng ký tài khoản để đóng góp bài viết trên Diễn đàn!");
      onNavigateToAuth('login');
      return;
    }
    onAddPost(newPost);
  };

  const handleLikePostPublic = (postId) => {
    if (!currentUser) {
      alert("Vui lòng đăng nhập để bình chọn bài viết yêu thích!");
      onNavigateToAuth('login');
      return;
    }
    onLikePost(postId);
  };

  const handleAddCommentPublic = (postId, newComment) => {
    if (!currentUser) {
      alert("Vui lòng đăng nhập để tham gia thảo luận!");
      onNavigateToAuth('login');
      return;
    }
    onAddComment(postId, newComment);
  };

  const renderSubjectIcon = (id) => {
    switch (id) {
      case 'toan':
        return (
          <svg stroke="currentColor" fill="none" strokeWidth="2.5" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" height="1em" width="1em">
            <line x1="18" y1="15" x2="12" y2="15"></line>
            <line x1="12" y1="15" x2="9" y2="21"></line>
            <line x1="9" y1="21" x2="6" y2="3"></line>
            <line x1="6" y1="3" x2="2" y2="3"></line>
          </svg>
        );
      case 'ly':
        return (
          <svg stroke="currentColor" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" height="1em" width="1em">
            <ellipse cx="12" cy="12" rx="3" ry="9" transform="rotate(45 12 12)"></ellipse>
            <ellipse cx="12" cy="12" rx="3" ry="9" transform="rotate(-45 12 12)"></ellipse>
            <circle cx="12" cy="12" r="2"></circle>
          </svg>
        );
      case 'anh':
        return (
          <svg stroke="currentColor" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" height="1em" width="1em">
            <circle cx="12" cy="12" r="10"></circle>
            <line x1="2" y1="12" x2="22" y2="12"></line>
            <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path>
          </svg>
        );
      case 'hoa':
        return (
          <svg stroke="currentColor" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" height="1em" width="1em">
            <path d="M10 2h4"></path>
            <path d="M12 2v6"></path>
            <path d="M8 8h8"></path>
            <path d="M8 8L4.5 16.5C3.5 19 5 22 8 22h8c3 0 4.5-3 3.5-5.5L16 8"></path>
          </svg>
        );
      case 'sinh':
        return (
          <svg stroke="currentColor" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" height="1em" width="1em">
            <path d="M2 22C2 12 10 4 22 2"></path>
            <path d="M22 2c-10 0-18 8-20 20"></path>
            <path d="M9 15c3-3 7-5 13-7"></path>
          </svg>
        );
      case 'van':
        return (
          <svg stroke="currentColor" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" height="1em" width="1em">
            <path d="M12 20h9"></path>
            <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
          </svg>
        );
      default:
        return <span>📚</span>;
    }
  };

  useEffect(() => {
    const fn = () => setScrolled(window.scrollY > 10);
    window.addEventListener('scroll', fn);
    return () => window.removeEventListener('scroll', fn);
  }, []);

  const scrollToSection = (e, id) => {
    e.preventDefault();
    const el = document.getElementById(id);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      setMobileMenuOpen(false);
    }
  };

  return (
    <div className="lp-root">

      {/* ── NAVBAR ── */}
      <nav className={`lp-nav${scrolled ? ' lp-nav--scrolled' : ''}`}>
        <div className="lp-nav__inner">
          <div className="lp-nav__logo" onClick={() => setActiveLandingView('home')} style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer' }}>
            <div className="lp-logo-box">E</div>
            <span>EduPath <em>AI</em></span>
          </div>

          <div className="lp-nav__links">
            <a href="#subjects" className={activeLandingView === 'subjects' ? 'lp-link--active' : ''} onClick={(e) => { e.preventDefault(); setActiveLandingView('subjects'); }}>Môn học</a>
            <a href="#features" className={activeLandingView === 'features' ? 'lp-link--active' : ''} onClick={(e) => { e.preventDefault(); setActiveLandingView('features'); }}>Tính năng</a>
            <a href="#forum" className={activeLandingView === 'forum' ? 'lp-link--active' : ''} onClick={(e) => { e.preventDefault(); setActiveLandingView('forum'); }}>Diễn đàn</a>
            <a href="#stats" className={activeLandingView === 'about' ? 'lp-link--active' : ''} onClick={(e) => { e.preventDefault(); setActiveLandingView('about'); }}>Về chúng tôi</a>
            <a href="#pricing" className={activeLandingView === 'pricing' ? 'lp-link--active' : ''} onClick={(e) => { e.preventDefault(); setActiveLandingView('pricing'); }}>Học phí</a>
          </div>

          <div className="lp-nav__cta">
            {currentUser ? (
              <div style={{ display: 'flex', alignItems: 'center', gap: '16px', position: 'relative' }}>
                <button 
                  className="lp-btn lp-btn--accent" 
                  onClick={() => onBackToDashboard('home')}
                  style={{
                    background: 'linear-gradient(135deg, var(--lp-accent), #22c55e)',
                    boxShadow: '0 4px 14px rgba(74,222,128,0.3)',
                    border: 'none',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '6px'
                  }}
                >
                  Vào học ngay 🚀
                </button>

                {/* Profile Avatar Trigger */}
                <div style={{ position: 'relative' }}>
                  <button 
                    onClick={() => setProfileDropdownOpen(!profileDropdownOpen)}
                    style={{
                      background: 'none',
                      border: 'none',
                      padding: 0,
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      outline: 'none'
                    }}
                  >
                    <div 
                      style={{
                        width: '38px',
                        height: '38px',
                        borderRadius: '50%',
                        background: 'linear-gradient(135deg, #6c5ce7, #a29bfe)',
                        color: '#fff',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        fontWeight: '800',
                        fontSize: '13px',
                        border: '2px solid rgba(255,255,255,0.2)',
                        boxShadow: '0 2px 10px rgba(0,0,0,0.15)'
                      }}
                    >
                      {currentUser.avatar || currentUser.name.slice(0,2).toUpperCase()}
                    </div>
                  </button>

                  {/* Profile Dropdown Menu */}
                  {profileDropdownOpen && (
                    <>
                      <div 
                        onClick={() => setProfileDropdownOpen(false)}
                        style={{
                          position: 'fixed',
                          top: 0, left: 0, right: 0, bottom: 0,
                          zIndex: 998
                        }}
                      />
                      <div 
                        className="lp-dropdown-menu animate-in"
                        style={{
                          position: 'absolute',
                          top: '46px',
                          right: 0,
                          width: '260px',
                          background: 'var(--bg-card, #ffffff)',
                          borderRadius: '14px',
                          boxShadow: '0 10px 30px rgba(0,0,0,0.15)',
                          border: '1px solid var(--border, #e2e8f0)',
                          padding: '16px',
                          zIndex: 999,
                          textAlign: 'left'
                        }}
                      >
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', paddingBottom: '12px', borderBottom: '1px solid var(--border, #f1f5f9)' }}>
                          <div 
                            style={{
                              width: '40px',
                              height: '40px',
                              borderRadius: '50%',
                              background: 'linear-gradient(135deg, #6c5ce7, #a29bfe)',
                              color: '#fff',
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center',
                              fontWeight: 'bold',
                              fontSize: '14px',
                              flexShrink: 0
                            }}
                          >
                            {currentUser.avatar || currentUser.name.slice(0,2).toUpperCase()}
                          </div>
                          <div style={{ minWidth: 0 }}>
                            <h4 style={{ margin: 0, fontSize: '13.5px', fontWeight: '700', color: 'var(--text-main, #1e293b)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                              {currentUser.name}
                            </h4>
                            <p style={{ margin: '2px 0 0', fontSize: '11px', color: 'var(--text-muted, #64748b)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                              {currentUser.email}
                            </p>
                            <span 
                              style={{
                                display: 'inline-block',
                                background: 'rgba(108,92,231,0.12)',
                                color: 'var(--primary, #6c5ce7)',
                                fontSize: '8.5px',
                                fontWeight: '800',
                                padding: '1px 6px',
                                borderRadius: '10px',
                                marginTop: '4px',
                                textTransform: 'uppercase'
                              }}
                            >
                              {currentUser.role === 'student' ? 'Học sinh' : (currentUser.role === 'teacher' ? 'Giáo viên' : 'Admin')}
                            </span>
                          </div>
                        </div>

                        <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', marginTop: '10px' }}>
                          <button 
                            onClick={() => { setProfileDropdownOpen(false); onBackToDashboard('home'); }}
                            style={{
                              display: 'flex',
                              alignItems: 'center',
                              gap: '10px',
                              width: '100%',
                              padding: '9px 10px',
                              background: 'none',
                              border: 'none',
                              borderRadius: '8px',
                              color: 'var(--text-secondary, #334155)',
                              fontSize: '13px',
                              fontWeight: '600',
                              cursor: 'pointer',
                              textAlign: 'left',
                              transition: 'background 0.2s'
                            }}
                            className="lp-dropdown-item"
                          >
                            💻 Bảng điều khiển
                          </button>
                          
                          <button 
                            onClick={() => { setProfileDropdownOpen(false); onBackToDashboard('settings'); }}
                            style={{
                              display: 'flex',
                              alignItems: 'center',
                              gap: '10px',
                              width: '100%',
                              padding: '9px 10px',
                              background: 'none',
                              border: 'none',
                              borderRadius: '8px',
                              color: 'var(--text-secondary, #334155)',
                              fontSize: '13px',
                              fontWeight: '600',
                              cursor: 'pointer',
                              textAlign: 'left',
                              transition: 'background 0.2s'
                            }}
                            className="lp-dropdown-item"
                          >
                            ⚙️ Thiết lập hồ sơ
                          </button>

                          <div style={{ height: '1px', background: 'var(--border, #f1f5f9)', margin: '4px 0' }} />

                          <button 
                            onClick={() => { setProfileDropdownOpen(false); onLogout(); }}
                            style={{
                              display: 'flex',
                              alignItems: 'center',
                              gap: '10px',
                              width: '100%',
                              padding: '9px 10px',
                              background: 'none',
                              border: 'none',
                              borderRadius: '8px',
                              color: '#ef4444',
                              fontSize: '13px',
                              fontWeight: '600',
                              cursor: 'pointer',
                              textAlign: 'left',
                              transition: 'background 0.2s'
                            }}
                            className="lp-dropdown-item lp-dropdown-item--logout"
                          >
                            🚪 Đăng xuất
                          </button>
                        </div>
                      </div>
                    </>
                  )}
                </div>
              </div>
            ) : (
              <>
                <button className="lp-btn lp-btn--ghost" onClick={() => onNavigateToAuth('login')}>Đăng nhập</button>
                <button className="lp-btn lp-btn--accent" onClick={() => onNavigateToAuth('signup')}>Đăng ký miễn phí</button>
              </>
            )}
          </div>

          <button className="lp-nav__hamburger" onClick={() => setMobileMenuOpen(!mobileMenuOpen)}>
            {mobileMenuOpen ? <HiX /> : <HiMenuAlt3 />}
          </button>
        </div>

        {mobileMenuOpen && (
          <div className="lp-mobile-menu">
            <a href="#subjects" onClick={(e) => { e.preventDefault(); setActiveLandingView('subjects'); setMobileMenuOpen(false); }}>Môn học</a>
            <a href="#features" onClick={(e) => { e.preventDefault(); setActiveLandingView('features'); setMobileMenuOpen(false); }}>Tính năng</a>
            <a href="#forum" onClick={(e) => { e.preventDefault(); setActiveLandingView('forum'); setMobileMenuOpen(false); }}>Diễn đàn</a>
            <a href="#stats" onClick={(e) => { e.preventDefault(); setActiveLandingView('about'); setMobileMenuOpen(false); }}>Về chúng tôi</a>
            <a href="#pricing" onClick={(e) => { e.preventDefault(); setActiveLandingView('pricing'); setMobileMenuOpen(false); }}>Học phí</a>
            
            {currentUser ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', marginTop: '12px', paddingTop: '12px', borderTop: '1px solid rgba(255,255,255,0.1)' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '4px' }}>
                  <div 
                    style={{
                      width: '38px',
                      height: '38px',
                      borderRadius: '50%',
                      background: 'linear-gradient(135deg, #6c5ce7, #a29bfe)',
                      color: '#fff',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontWeight: 'bold',
                      fontSize: '13px'
                    }}
                  >
                    {currentUser.avatar || currentUser.name.slice(0,2).toUpperCase()}
                  </div>
                  <div>
                    <h4 style={{ margin: 0, fontSize: '13.5px', fontWeight: '700', color: '#fff' }}>{currentUser.name}</h4>
                    <p style={{ margin: '2px 0 0', fontSize: '11px', color: 'rgba(255,255,255,0.6)' }}>{currentUser.email}</p>
                  </div>
                </div>
                
                <button 
                  className="lp-btn lp-btn--accent" 
                  style={{ width: '100%', justifyContent: 'center' }} 
                  onClick={() => { onBackToDashboard('home'); setMobileMenuOpen(false); }}
                >
                  Vào học ngay 🚀
                </button>
                <button 
                  className="lp-btn lp-btn--ghost" 
                  style={{ width: '100%', justifyContent: 'center', borderColor: '#f87171', color: '#f87171' }} 
                  onClick={() => { onLogout(); setMobileMenuOpen(false); }}
                >
                  Đăng xuất
                </button>
              </div>
            ) : (
              <div style={{ display: 'flex', gap: 10, marginTop: 8 }}>
                <button className="lp-btn lp-btn--ghost" style={{ flex: 1 }} onClick={() => { onNavigateToAuth('login'); setMobileMenuOpen(false); }}>Đăng nhập</button>
                <button className="lp-btn lp-btn--accent" style={{ flex: 1 }} onClick={() => { onNavigateToAuth('signup'); setMobileMenuOpen(false); }}>Đăng ký</button>
              </div>
            )}
          </div>
        )}
      </nav>

      <div style={{ paddingTop: '68px' }}>
        {activeLandingView === 'home' && (
          <div className="animate-fade">

            {/* ── HERO ── */}
            <section className="lp-hero">
        <div className="lp-hero__left">
          <div className="lp-hero__title-row">
            <h2 className="lp-hero__title-main">Nền tảng</h2>
            <span className="lp-hero__title-badge">EduPath AI</span>
          </div>

          <div className="lp-hero__highlight-box">
            Luyện thi THPTQG
            <span className="lp-hero__cursor">|</span>
          </div>

          <p className="lp-hero__sub">
            Đầy đủ tài liệu, bài luyện, phương pháp và từ vựng giúp bạn chinh phục kỳ thi THPTQG dễ dàng hơn mỗi ngày.
          </p>

          <div className="lp-hero__follow-pill">
            <span className="lp-hero__follow-text">Follow us on</span>
            <button className="lp-hero__social-btn lp-hero__social-btn--fb" title="Facebook">
              <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 320 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path></svg>
            </button>
            <button className="lp-hero__social-btn lp-hero__social-btn--tt" title="TikTok">
              <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 448 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M448,209.91a210.06,210.06,0,0,1-122.77-39.25V349.38A162.55,162.55,0,1,1,185,188.07c8.89,0,17.44,1,25.74,2.9V273.7a81.24,81.24,0,1,0-45.74,75.68V209.91c0-43.1,34.9-78,78-78a77.34,77.34,0,0,1,47,15.82V0h81.38a206.52,206.52,0,0,0,76.57,69.57v81.38a211,211,0,0,1-76.57-21Z"></path></svg>
            </button>
          </div>

          <div className="lp-hero__actions">
            <button className="lp-hero__btn-white" onClick={() => currentUser ? onBackToDashboard('forum') : onNavigateToAuth('signup')}>
              Bài viết của EduPath
              <HiArrowRight />
            </button>
            <button className="lp-hero__btn-explore" onClick={(e) => currentUser ? onBackToDashboard('library') : scrollToSection(e, 'subjects')}>
              <svg stroke="currentColor" fill="none" strokeWidth="2.5" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" height="1.1em" width="1.1em" xmlns="http://www.w3.org/2000/svg"><circle cx="12" cy="12" r="10"></circle><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"></polygon></svg>
              Khám phá tài liệu miễn phí
            </button>
          </div>
        </div>

        <div className="lp-hero__right">
          <FooterSunMascot />
        </div>
      </section>

      {/* Wavy divider */}
      <div className="lp-wave">
        <svg viewBox="0 0 1440 80" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M0,40 C240,80 480,0 720,40 C960,80 1200,0 1440,40 L1440,80 L0,80 Z" fill="#ffffff"/>
        </svg>
      </div>

      {/* ── SUBJECT CARDS ── */}
      <section id="subjects" className="lp-subjects">
        <div className="lp-container">
          <div className="lp-section-header lp-section-header--light">
            <span className="lp-eyebrow lp-eyebrow--dark">Danh mục môn học</span>
            <h2>Chinh phục từng môn theo từng khối thi</h2>
            <p>Giáo trình được thiết kế riêng biệt cho A01, B00 và D01 — bám sát cấu trúc đề thi THPTQG mới nhất.</p>
          </div>

          <div className="lp-cards-row">
            {SUBJECTS.map((s) => (
              <div key={s.id} className="lp-subject-card" style={{ '--card-bg': s.bg }} onClick={() => setActiveLandingView('subjects')}>
                {s.isFree && <span className="lp-card-free-badge">FREE</span>}
                <div className="lp-card-icon-container">
                  {renderSubjectIcon(s.id)}
                </div>
                <div className="lp-card-info">
                  <h3>{s.label}</h3>
                  <p>{s.desc}</p>
                </div>
                <div className="lp-card-footer">
                  <span className="lp-card-count">{s.count}</span>
                  <div className="lp-card-combos">
                    {s.combos.map(c => <span key={c} className="lp-card-combo-tag">{c}</span>)}
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div style={{ textAlign: 'center', marginTop: 40 }}>
            <button className="lp-btn lp-btn--primary lp-btn--lg" onClick={() => currentUser ? onBackToDashboard('library') : onNavigateToAuth('signup')}>
              Xem toàn bộ tài liệu <HiArrowRight />
            </button>
          </div>
        </div>
      </section>

      {/* ── FEATURED PREMIUM COURSES ── */}
      <section className="lp-subjects" style={{ background: '#f8faf8', borderTop: '1px solid var(--border)', padding: '60px 0' }}>
        <div className="lp-container">
          <div className="lp-section-header lp-section-header--light" style={{ marginBottom: '40px' }}>
            <span className="lp-eyebrow">Khóa Học Premium Nổi Bật</span>
            <h2>Chương Trình Luyện Thi THPTQG Chuyên Sâu</h2>
            <p>Đăng ký khóa học của các giáo viên hàng đầu để nhận lộ trình thích ứng thông minh.</p>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '24px', maxWidth: '1000px', margin: '0 auto' }}>
            {FEATURED_COURSES.map(course => (
              <div 
                key={course.id} 
                className="card landing-card" 
                style={{ 
                  display: 'flex', 
                  flexDirection: 'column', 
                  justifyContent: 'space-between',
                  overflow: 'hidden',
                  padding: 0,
                  height: '100%',
                  background: 'var(--bg-card)',
                  border: '1px solid var(--border)',
                  borderRadius: 'var(--radius-lg)'
                }}
              >
                <div style={{ background: course.imageBg, height: '110px', padding: '16px', color: '#fff', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
                  <span style={{ background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(4px)', width: 'fit-content', padding: '4px 10px', borderRadius: '12px', fontSize: '10px', fontWeight: 'bold' }}>
                    {course.subject}
                  </span>
                  <h4 style={{ fontSize: '14.5px', fontWeight: 'bold', textShadow: '0 2px 4px rgba(0,0,0,0.2)', margin: 0 }}>{course.title}</h4>
                </div>

                <div style={{ padding: '20px', flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'space-between', gap: '14px' }}>
                  <div>
                    <p style={{ fontSize: '12.5px', color: 'var(--text-secondary)', margin: 0 }}>Giảng viên: <strong>{course.teacherName}</strong></p>
                    <p style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '4px', marginBottom: 0 }}>{course.duration}</p>
                    
                    <div style={{ display: 'flex', gap: '16px', marginTop: '12px', fontSize: '12px', color: 'var(--text-secondary)' }}>
                      <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><HiStar style={{ color: '#f1c40f' }} /> {course.rating}</span>
                      <span>👤 {course.students} học viên</span>
                    </div>
                  </div>

                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '10px', paddingTop: '12px', borderTop: '1px solid var(--border)' }}>
                    <span style={{ fontSize: '17px', color: 'var(--accent-orange)', fontWeight: '800' }}>{course.price}đ</span>
                    <button 
                      className="btn-primary" 
                      style={{ padding: '8px 16px', fontSize: '12px' }} 
                      onClick={() => setSelectedPreviewCourse(course)}
                    >
                      Xem đề cương
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── LEADERBOARD SECTION ── */}
      <section id="leaderboard" className="lp-leaderboard-section">
        <div className="lp-container">
          <div className="lp-section-header lp-section-header--light" style={{ marginBottom: '40px' }}>
            <span className="lp-eyebrow" style={{ display: 'flex', alignItems: 'center', gap: '6px', width: 'fit-content', margin: '0 auto 14px' }}>
              <HiSparkles style={{ color: 'var(--primary)' }} /> Vinh danh học viên
            </span>
            <h2>Bảng Xếp Hạng Thành Tích Học Tập THPTQG 2026</h2>
            <p>Học tập liên tục, bứt phá giới hạn và vươn lên dẫn đầu bảng xếp hạng cùng EduPath AI.</p>
          </div>

          <div className="leaderboard-container">
            <div className="leaderboard-header">
              <div style={{ display: 'flex', gap: '8px' }}>
                <button 
                  className={`badge-pill ${leaderboardTab === 'score' ? 'active' : ''}`}
                  onClick={() => setLeaderboardTab('score')}
                  style={{
                    border: '1px solid var(--border)',
                    background: leaderboardTab === 'score' ? 'var(--primary)' : 'var(--bg-main)',
                    color: leaderboardTab === 'score' ? '#fff' : 'var(--text-secondary)',
                    padding: '8px 16px',
                    borderRadius: '20px',
                    fontSize: '12px',
                    cursor: 'pointer',
                    transition: 'all 0.2s'
                  }}
                >
                  🎯 Theo điểm thi thử
                </button>
                <button 
                  className={`badge-pill ${leaderboardTab === 'streak' ? 'active' : ''}`}
                  onClick={() => setLeaderboardTab('streak')}
                  style={{
                    border: '1px solid var(--border)',
                    background: leaderboardTab === 'streak' ? 'var(--primary)' : 'var(--bg-main)',
                    color: leaderboardTab === 'streak' ? '#fff' : 'var(--text-secondary)',
                    padding: '8px 16px',
                    borderRadius: '20px',
                    fontSize: '12px',
                    cursor: 'pointer',
                    transition: 'all 0.2s'
                  }}
                >
                  🔥 Theo chuỗi học tập (Streak)
                </button>
              </div>
              <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Cập nhật 5 phút trước</span>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {[...MOCK_LEADERBOARD]
                .sort((a, b) => leaderboardTab === 'score' ? parseFloat(b.actual) - parseFloat(a.actual) : b.streak - a.streak)
                .map((student, index) => {
                  const displayRank = index + 1;
                  let rankClass = "rank-other";
                  let rowClass = "";
                  if (displayRank === 1) { rankClass = "rank-1"; rowClass = "top-1"; }
                  else if (displayRank === 2) { rankClass = "rank-2"; rowClass = "top-2"; }
                  else if (displayRank === 3) { rankClass = "rank-3"; rowClass = "top-3"; }

                  return (
                    <div key={student.name} className={`leaderboard-row ${rowClass}`}>
                      <div className={`rank-badge ${rankClass}`}>{displayRank}</div>
                      <div className="leaderboard-avatar">{student.avatar}</div>
                      <div>
                        <div className="leaderboard-name">{student.name}</div>
                        <div style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '2px' }}>{student.badge}</div>
                      </div>
                      <div style={{ fontSize: '12.5px', color: 'var(--text-secondary)', fontWeight: 600 }}>{student.combo}</div>
                      <div style={{ fontSize: '13px', color: 'var(--primary)', fontWeight: 'bold' }}>
                        🎯 {student.actual}/{student.target}đ
                      </div>
                      <div style={{ fontSize: '13px', color: 'var(--accent-orange)', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '4px' }}>
                        🔥 {student.streak} ngày
                      </div>
                    </div>
                  );
                })}
            </div>
          </div>
        </div>
      </section>

      {/* ── CURRICULUM PREVIEW MODAL ── */}
      {selectedPreviewCourse && (
        <div className="checkout-overlay" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 10000 }}>
          <div className="checkout-modal animate-in" style={{ maxWidth: '500px', width: '90%', position: 'relative', background: 'var(--bg-card)' }}>
            <button 
              onClick={() => setSelectedPreviewCourse(null)}
              style={{ position: 'absolute', top: '16px', right: '16px', border: 'none', background: 'none', color: 'var(--text-secondary)', fontSize: '20px', cursor: 'pointer' }}
            >
              <HiX />
            </button>
            <div style={{ display: 'flex', gap: '8px', alignItems: 'center', marginBottom: '10px' }}>
              <span className="badge-pill" style={{ background: 'var(--primary-bg)', color: 'var(--primary)', fontSize: '10px', fontWeight: 'bold' }}>
                Đề cương bài học
              </span>
            </div>
            <h3 style={{ fontSize: '17px', fontWeight: 'bold', marginBottom: '4px', color: 'var(--text-main)' }}>
              {selectedPreviewCourse.title}
            </h3>
            <p style={{ fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '20px' }}>
              Giảng dạy bởi: {selectedPreviewCourse.teacherName}
            </p>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', maxHeight: '280px', overflowY: 'auto', paddingRight: '4px', marginBottom: '24px' }}>
              {selectedPreviewCourse.lessons.map((lesson, idx) => (
                <div 
                  key={idx}
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    padding: '12px 14px',
                    borderRadius: 'var(--radius-md)',
                    background: 'var(--bg-main)',
                    border: '1px solid var(--border)'
                  }}
                >
                  <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
                    <span style={{ fontSize: '13px', color: 'var(--primary)', fontWeight: 'bold' }}>{idx + 1}</span>
                    <div>
                      <h5 style={{ fontSize: '12.5px', fontWeight: '600', color: 'var(--text-main)', margin: 0 }}>{lesson.name}</h5>
                      <span style={{ fontSize: '10px', color: 'var(--text-muted)' }}>{lesson.duration}</span>
                    </div>
                  </div>

                  {lesson.isFree ? (
                    <button 
                      className="badge-pill" 
                      style={{ background: 'rgba(0,184,148,0.12)', color: 'var(--accent-green)', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', padding: '6px 12px', fontSize: '10.5px', fontWeight: 'bold' }}
                      onClick={() => {
                        alert(`Bắt đầu xem thử bài học: "${lesson.name}"!`);
                        setSelectedPreviewCourse(null);
                      }}
                    >
                      <HiPlay /> Học thử
                    </button>
                  ) : (
                    <span style={{ fontSize: '11px', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                      <HiLockClosed /> Premium
                    </span>
                  )}
                </div>
              ))}
            </div>

            <button 
              className="btn-primary" 
              style={{ width: '100%' }}
              onClick={() => {
                setSelectedPreviewCourse(null);
                if (currentUser) {
                  onBackToDashboard('courses');
                } else {
                  onNavigateToAuth('signup');
                }
              }}
            >
              Mở khóa toàn bộ khóa học ngay
            </button>
          </div>
        </div>
      )}

      {/* ── STATS ── */}
      <section id="stats" className="lp-stats-section">
        <div className="lp-container">
          <div className="lp-stats-grid">
            {STATS.map((s, i) => (
              <div key={i} className="lp-stat-item">
                <span className="lp-stat-icon">{s.icon}</span>
                <span className="lp-stat-value">{s.value}</span>
                <span className="lp-stat-label">{s.label}</span>
              </div>
            ))}
          </div>
          <div className="lp-stats-tagline">
            <p>Giúp bạn đạt được mục tiêu hiệu quả qua ứng dụng công nghệ và nghiên cứu khoa học vào giảng dạy</p>
          </div>
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section id="features" className="lp-features-section">
        <div className="lp-container">
          <div className="lp-section-header">
            <span className="lp-eyebrow">Tại sao chọn EduPath AI?</span>
            <h2>Học thông minh hơn, không chỉ học nhiều hơn</h2>
          </div>

          <div className="lp-features-grid">
            {FEATURES.map((f, i) => (
              <div key={i} className="lp-feature-card">
                <div className="lp-feature-icon">{f.icon}</div>
                <h3>{f.title}</h3>
                <p>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── PRICING ── */}
      <section id="pricing" className="lp-pricing-section">
        <div className="lp-container">
          <div className="lp-section-header">
            <span className="lp-eyebrow">Học phí minh bạch</span>
            <h2>Bắt đầu miễn phí, nâng cấp khi sẵn sàng</h2>
          </div>

          <div className="lp-pricing-row">
            <div className="lp-price-card">
              <div className="lp-price-tier">GÓI CƠ BẢN</div>
              <div className="lp-price-amount">0đ<span>/mãi mãi</span></div>
              <ul className="lp-price-features">
                <li><HiCheck /> Làm 5 đề thi thử mẫu</li>
                <li><HiCheck /> Xem 2 bài giảng đầu mỗi khóa</li>
                <li><HiCheck /> Tải slide tóm tắt công thức</li>
              </ul>
              <button 
                className="lp-btn lp-btn--outline lp-btn--full" 
                onClick={() => currentUser ? onBackToDashboard('home') : onNavigateToAuth('signup')}
              >
                {currentUser ? "Bắt đầu học ngay" : "Đăng ký miễn phí"}
              </button>
            </div>

            <div className="lp-price-card lp-price-card--featured">
              <div className="lp-price-badge">Bán chạy nhất ⚡</div>
              <div className="lp-price-tier">PREMIUM PRO</div>
              <div className="lp-price-amount">599.000đ<span>/trọn đời</span></div>
              <ul className="lp-price-features">
                <li><HiCheck /> <strong>Mở khóa toàn bộ</strong> video & đề thi</li>
                <li><HiCheck /> <strong>AI phân tích</strong> lỗ hổng tức thì</li>
                <li><HiCheck /> Lộ trình <strong>cá nhân hóa</strong> tự động</li>
                <li><HiCheck /> <strong>EduBot AI</strong> hỏi đáp không giới hạn</li>
                <li><HiCheck /> Hỗ trợ trực tiếp <strong>giáo viên bộ môn</strong></li>
              </ul>
              <button 
                className="lp-btn lp-btn--accent lp-btn--full" 
                onClick={() => currentUser ? onBackToDashboard('courses') : onNavigateToAuth('signup')}
              >
                {currentUser ? "Đăng ký khóa học ngay" : "Nâng cấp Premium Pro"} <HiLightningBolt />
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* ── CTA BANNER ── */}
      <section className="lp-cta-banner">
        <div className="lp-container lp-cta-inner">
          <div className="lp-cta-mascot">🎓</div>
          <div>
            <h2>Sẵn sàng chinh phục THPTQG?</h2>
            <p>Tham gia cùng 42,500+ học sinh đang học mỗi ngày với EduPath AI.</p>
          </div>
          <button 
            className="lp-btn lp-btn--white lp-btn--lg" 
            onClick={() => currentUser ? onBackToDashboard('home') : onNavigateToAuth('signup')}
          >
            {currentUser ? "Đến bảng điều khiển" : "Bắt đầu ngay hôm nay"} <HiArrowRight />
          </button>
        </div>
      </section>
          </div>
        )}

        {/* ================= 2. SUBJECTS DEDICATED PAGE ================= */}
        {activeLandingView === 'subjects' && (
          <div className="lp-container" style={{ padding: '40px 28px 80px' }}>
            <button 
              onClick={() => setActiveLandingView('home')}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--primary, #6c5ce7)',
                fontWeight: 'bold',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                fontSize: '14.5px',
                marginBottom: '28px',
                padding: 0
              }}
            >
              ← Quay lại trang chủ
            </button>

            <div className="lp-modal-grid">
              <div className="lp-modal-img-col" style={{ backgroundImage: `url(${teacherMathImg})`, minHeight: '450px', borderRadius: '16px', overflow: 'hidden' }}>
                <div className="lp-modal-img-overlay">
                  <span className="lp-modal-badge">🦉 Đội Ngũ Sư Phạm 8.0+</span>
                  <h3>Thầy Cô Đồng Hành Chạm Mốc 28.5+ THPTQG</h3>
                </div>
              </div>
              <div className="lp-modal-info-col" style={{ padding: '0 10px' }}>
                <span className="lp-eyebrow">CHƯƠNG TRÌNH HỌC TỐI ƯU</span>
                <h2 style={{ fontSize: '32px', fontWeight: '900', color: 'var(--lp-dark)', margin: '10px 0 18px 0' }}>Hệ thống chuyên đề môn học thi THPTQG tốt nhất</h2>
                <p style={{ fontSize: '14.5px', lineHeight: '1.7', color: 'var(--text-secondary)' }}>Giáo trình giảng dạy được kiểm định nghiêm ngặt bởi các chuyên gia sư phạm hàng đầu Việt Nam, chia nhỏ thành các cấp độ từ cơ bản (nhận biết, thông hiểu) đến cực khó (vận dụng cao).</p>
                
                <div style={{ display: 'flex', flexDirection: 'column', gap: '16px', marginTop: '24px' }}>
                  <div style={{ display: 'flex', gap: '14px', alignItems: 'flex-start' }}>
                    <span style={{ fontSize: '24px', background: 'rgba(74,222,128,0.15)', padding: '10px', borderRadius: '12px' }}>📐</span>
                    <div>
                      <strong style={{ fontSize: '15px', color: 'var(--text-main)' }}>Khối A01: Toán - Vật Lý - Tiếng Anh</strong>
                      <p style={{ margin: '4px 0 0 0', fontSize: '12.5px', color: 'var(--text-secondary)', lineHeight: '1.6' }}>Trọng tâm chuyên đề khảo sát hàm số, dao động điều hòa, sóng cơ học và ngữ pháp đọc hiểu tiếng Anh thực tế.</p>
                    </div>
                  </div>
                  <div style={{ display: 'flex', gap: '14px', alignItems: 'flex-start' }}>
                    <span style={{ fontSize: '24px', background: 'rgba(243,156,18,0.15)', padding: '10px', borderRadius: '12px' }}>🧬</span>
                    <div>
                      <strong style={{ fontSize: '15px', color: 'var(--text-main)' }}>Khối B00: Toán - Hóa Học - Sinh Học</strong>
                      <p style={{ margin: '4px 0 0 0', fontSize: '12.5px', color: 'var(--text-secondary)', lineHeight: '1.6' }}>Mở khóa toàn diện chuyên đề Este nâng cao, bài toán di truyền & cơ chế tiến hóa sinh học bám sát cấu trúc đề mới.</p>
                    </div>
                  </div>
                  <div style={{ display: 'flex', gap: '14px', alignItems: 'flex-start' }}>
                    <span style={{ fontSize: '24px', background: 'rgba(108,92,231,0.15)', padding: '10px', borderRadius: '12px' }}>✍️</span>
                    <div>
                      <strong style={{ fontSize: '15px', color: 'var(--text-main)' }}>Khối D01: Toán - Ngữ Văn - Tiếng Anh</strong>
                      <p style={{ margin: '4px 0 0 0', fontSize: '12.5px', color: 'var(--text-secondary)', lineHeight: '1.6' }}>Ôn luyện phương pháp nghị luận văn học, tư duy đọc hiểu và nâng cao điểm số viết văn bứt phá giới hạn.</p>
                    </div>
                  </div>
                </div>

                <button 
                  className="lp-btn lp-btn--accent lp-btn--full lp-btn--lg" 
                  style={{ marginTop: '36px' }}
                  onClick={() => { if (currentUser) { onBackToDashboard('courses'); } else { onNavigateToAuth('signup'); } }}
                >
                  {currentUser ? "Khám phá kho khóa học ngay 🚀" : "Đăng ký trải nghiệm bài giảng thử miễn phí"}
                </button>
              </div>
            </div>

            <div style={{ height: '1px', background: 'var(--border, #e2e8f0)', margin: '50px 0' }} />

            {/* Real Taught Courses Grid Section */}
            <div className="lp-section-header lp-section-header--light" style={{ textAlign: 'center', marginBottom: '40px' }}>
              <span className="lp-eyebrow" style={{ display: 'inline-block', background: 'rgba(108,92,231,0.12)', color: 'var(--primary)', padding: '6px 16px', borderRadius: '20px', fontWeight: 'bold', fontSize: '12px', textTransform: 'uppercase' }}>
                Danh mục khóa học hệ thống
              </span>
              <h2 style={{ fontSize: '28px', fontWeight: '800', marginTop: '12px', color: 'var(--text-main)' }}>Các Khóa Học Tiêu Biểu Dành Cho Bạn</h2>
              <p style={{ color: 'var(--text-secondary)', maxWidth: '600px', margin: '8px auto 0', fontSize: '14px' }}>
                Học tập trực tiếp cùng đội ngũ thầy cô giáo nổi tiếng, chất lượng giảng dạy chuẩn sư phạm 8.0+ điểm.
              </p>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(310px, 1fr))', gap: '28px', maxWidth: '1100px', margin: '0 auto' }}>
              {FEATURED_COURSES.map(course => {
                let teacherDesc = "";
                let teacherAvatar = "";
                let teacherAvatarBg = "";
                if (course.id === 1) {
                  teacherDesc = "Thủ khoa Toán K60 ĐHQGHN, 5+ năm luyện thi chuyên sâu THPTQG, chuyên gia Casio giải nhanh.";
                  teacherAvatar = "TA";
                  teacherAvatarBg = "linear-gradient(135deg, #6c5ce7, #a29bfe)";
                } else if (course.id === 2) {
                  teacherDesc = "Thạc sĩ Vật lý chất lượng cao ĐH Sư Phạm, Cựu giáo viên chuyên lý THPT, 8+ năm kinh nghiệm.";
                  teacherAvatar = "TH";
                  teacherAvatarBg = "linear-gradient(135deg, #e17055, #fab1a0)";
                } else {
                  teacherDesc = "Thạc sĩ Ngôn ngữ học quốc tế, IELTS 8.5, giảng viên chuyên luyện thi Đại học khối A01, D01.";
                  teacherAvatar = "QC";
                  teacherAvatarBg = "linear-gradient(135deg, #00b894, #55efc4)";
                }

                return (
                  <div key={course.id} className="card landing-card" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between', overflow: 'hidden', padding: 0, height: '100%', background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)', boxShadow: '0 4px 15px rgba(0,0,0,0.05)', transition: 'all 0.3s' }}>
                    <div style={{ background: course.imageBg, height: '120px', padding: '20px', color: '#fff', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', position: 'relative' }}>
                      <span style={{ background: 'rgba(255,255,255,0.22)', backdropFilter: 'blur(6px)', width: 'fit-content', padding: '4px 12px', borderRadius: '20px', fontSize: '10.5px', fontWeight: '800', letterSpacing: '0.5px', textTransform: 'uppercase' }}>
                        {course.subject}
                      </span>
                      <h4 style={{ fontSize: '16px', fontWeight: '800', textShadow: '0 2px 4px rgba(0,0,0,0.35)', margin: 0, lineHeight: '1.4' }}>{course.title}</h4>
                    </div>

                    <div style={{ padding: '24px', flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'space-between', gap: '18px' }}>
                      
                      {/* Teacher Details */}
                      <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
                        <div style={{ width: '40px', height: '40px', borderRadius: '50%', background: teacherAvatarBg, color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', fontSize: '13.5px', flexShrink: 0, boxShadow: '0 2px 6px rgba(0,0,0,0.1)' }}>
                          {teacherAvatar}
                        </div>
                        <div>
                          <strong style={{ fontSize: '14px', color: 'var(--text-main)', display: 'block' }}>Giáo viên: {course.teacherName}</strong>
                          <p style={{ margin: '4px 0 0', fontSize: '11.5px', color: 'var(--text-muted)', lineHeight: '1.5' }}>{teacherDesc}</p>
                        </div>
                      </div>

                      <div style={{ borderTop: '1px dashed var(--border)', borderBottom: '1px dashed var(--border)', padding: '12px 0', display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '12px', color: 'var(--text-secondary)' }}>
                        <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><HiStar style={{ color: '#f1c40f', fontSize: '14px' }} /> <strong>{course.rating}</strong> (Đánh giá)</span>
                        <span>👤 <strong>{course.students}</strong> học viên</span>
                      </div>

                      <div style={{ fontSize: '12.5px', color: 'var(--text-secondary)' }}>
                        📖 Chi tiết: <strong style={{ color: 'var(--primary)' }}>{course.duration}</strong>
                      </div>

                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '6px' }}>
                        <div>
                          <span style={{ fontSize: '10px', color: 'var(--text-muted)', display: 'block', textTransform: 'uppercase' }}>Học phí trọn gói</span>
                          <span style={{ fontSize: '19px', color: 'var(--accent-orange)', fontWeight: '800' }}>{course.price}đ</span>
                        </div>
                        <div style={{ display: 'flex', gap: '8px' }}>
                          <button 
                            className="lp-btn lp-btn--outline" 
                            style={{ padding: '8px 14px', fontSize: '11.5px', fontWeight: 'bold' }} 
                            onClick={() => setSelectedPreviewCourse(course)}
                          >
                            Đề cương
                          </button>
                          <button 
                            className="lp-btn lp-btn--accent" 
                            style={{ padding: '8px 14px', fontSize: '11.5px', fontWeight: 'bold' }} 
                            onClick={() => { if (currentUser) { onBackToDashboard('courses'); } else { onNavigateToAuth('signup'); } }}
                          >
                            Đăng ký
                          </button>
                        </div>
                      </div>

                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* ================= 3. AI FEATURES DEDICATED PAGE ================= */}
        {activeLandingView === 'features' && (
          <div className="lp-container" style={{ padding: '40px 28px 80px' }}>
            <button 
              onClick={() => setActiveLandingView('home')}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--primary, #6c5ce7)',
                fontWeight: 'bold',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                fontSize: '14.5px',
                marginBottom: '28px',
                padding: 0
              }}
            >
              ← Quay lại trang chủ
            </button>

            <div className="lp-modal-grid">
              <div className="lp-modal-img-col" style={{ backgroundImage: `url(${studentLearningImg})`, minHeight: '450px', borderRadius: '16px', overflow: 'hidden' }}>
                <div className="lp-modal-img-overlay">
                  <span className="lp-modal-badge" style={{ background: '#3b82f6' }}>⚡ Công Nghệ Adaptive AI</span>
                  <h3>Chẩn Đoán Lỗ Hổng & Cá Nhân Hóa Lộ Trình</h3>
                </div>
              </div>
              <div className="lp-modal-info-col" style={{ padding: '0 10px' }}>
                <span className="lp-eyebrow">TÍNH NĂNG ĐỘT PHÁ</span>
                <h2 style={{ fontSize: '32px', fontWeight: '900', color: 'var(--lp-dark)', margin: '10px 0 18px 0' }}>Phương pháp học thích ứng thông minh vượt trội</h2>
                <p style={{ fontSize: '14.5px', lineHeight: '1.7', color: 'var(--text-secondary)' }}>Hệ thống tích hợp trí tuệ nhân tạo (AI-assisted Learning System) mô phỏng chính xác phương pháp kèm cặp 1-1 của giáo sư chuyên nghiệp để tối ưu thời gian học.</p>
                
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginTop: '24px' }}>
                  <div style={{ background: 'var(--bg-card, #ffffff)', padding: '16px', borderRadius: '12px', border: '1px solid var(--border)' }}>
                    <strong style={{ fontSize: '14px', display: 'block', color: 'var(--primary)', fontWeight: 'bold' }}>🔍 Chẩn đoán tức thì</strong>
                    <span style={{ fontSize: '12px', color: 'var(--text-secondary)', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>Chỉ ra chính xác lỗ hổng kiến thức sau mỗi đề làm thử bằng mạng nơ-ron phân tích hành vi.</span>
                  </div>
                  <div style={{ background: 'var(--bg-card, #ffffff)', padding: '16px', borderRadius: '12px', border: '1px solid var(--border)' }}>
                    <strong style={{ fontSize: '14px', display: 'block', color: 'var(--accent-orange)', fontWeight: 'bold' }}>🗺 Lộ trình động thích ứng</strong>
                    <span style={{ fontSize: '12px', color: 'var(--text-secondary)', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>Bản đồ học tập cá nhân hóa tự cập nhật theo điểm yếu và thời gian học tập thực tế mỗi ngày.</span>
                  </div>
                  <div style={{ background: 'var(--bg-card, #ffffff)', padding: '16px', borderRadius: '12px', border: '1px solid var(--border)' }}>
                    <strong style={{ fontSize: '14px', display: 'block', color: 'var(--accent-green)', fontWeight: 'bold' }}>📝 Đề sửa sai chuyên biệt</strong>
                    <span style={{ fontSize: '12px', color: 'var(--text-secondary)', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>AI tự sinh các bộ câu hỏi bù đắp hổng tập trung đúng vào các dạng bài học sinh làm sai.</span>
                  </div>
                  <div style={{ background: 'var(--bg-card, #ffffff)', padding: '16px', borderRadius: '12px', border: '1px solid var(--border)' }}>
                    <strong style={{ fontSize: '14px', display: 'block', color: '#8b5cf6', fontWeight: 'bold' }}>💬 Trợ lý EduBot 24/7</strong>
                    <span style={{ fontSize: '12px', color: 'var(--text-secondary)', display: 'block', marginTop: '6px', lineHeight: '1.5' }}>Giải đáp cực kỳ chi tiết phương pháp bấm máy Casio, gợi ý từ vựng bám sát mọi lúc mọi nơi.</span>
                  </div>
                </div>

                <button 
                  className="lp-btn lp-btn--accent lp-btn--full lp-btn--lg" 
                  style={{ marginTop: '36px' }}
                  onClick={() => { if (currentUser) { onBackToDashboard('path'); } else { onNavigateToAuth('signup'); } }}
                >
                  {currentUser ? "Xem lộ trình AI của bạn 🚀" : "Bắt đầu học thử cùng AI miễn phí"}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* ================= 4. ABOUT US DEDICATED PAGE ================= */}
        {activeLandingView === 'about' && (
          <div className="lp-container" style={{ padding: '40px 28px 80px' }}>
            <button 
              onClick={() => setActiveLandingView('home')}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--primary, #6c5ce7)',
                fontWeight: 'bold',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                fontSize: '14.5px',
                marginBottom: '28px',
                padding: 0
              }}
            >
              ← Quay lại trang chủ
            </button>

            <div className="lp-modal-grid">
              <div className="lp-modal-img-col" style={{ backgroundImage: `url(${educatorsTeamImg})`, minHeight: '450px', borderRadius: '16px', overflow: 'hidden' }}>
                <div className="lp-modal-img-overlay">
                  <span className="lp-modal-badge" style={{ background: '#10b981' }}>🎓 Sứ Mệnh Chuyển Đổi Số</span>
                  <h3>Công Nghệ Tiên Phong · Giáo Dục Tận Tâm</h3>
                </div>
              </div>
              <div className="lp-modal-info-col" style={{ padding: '0 10px' }}>
                <span className="lp-eyebrow">VỀ CHÚNG TÔI</span>
                <h2 style={{ fontSize: '32px', fontWeight: '900', color: 'var(--lp-dark)', margin: '10px 0 18px 0' }}>Đại diện tiêu biểu đổi mới sáng tạo giáo dục</h2>
                <p style={{ fontSize: '14.5px', lineHeight: '1.7', color: 'var(--text-secondary)' }}>EduPath AI tự hào mang lại một giải pháp luyện thi THPTQG thích ứng số một Việt Nam, ứng dụng tinh hoa công nghệ trí tuệ nhân tạo và giáo trình giảng dạy chuyên sâu.</p>
                
                <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', marginTop: '24px', fontSize: '13.5px', color: 'var(--text-secondary)' }}>
                  <div style={{ borderLeft: '4px solid var(--primary)', paddingLeft: '16px', background: 'var(--bg-card)', padding: '14px 16px', borderRadius: '0 12px 12px 0', border: '1px solid var(--border)', borderLeftWidth: '4px' }}>
                    <strong style={{ color: 'var(--text-main)', fontSize: '14.5px' }}>Sứ mệnh giáo dục:</strong> Phổ cập giáo dục chất lượng cao cá nhân hóa đến mọi học sinh Việt Nam, bất kể vùng miền với mức chi phí tối giản.
                  </div>
                  <div style={{ borderLeft: '4px solid var(--accent-orange)', paddingLeft: '16px', background: 'var(--bg-card)', padding: '14px 16px', borderRadius: '0 12px 12px 0', border: '1px solid var(--border)', borderLeftWidth: '4px' }}>
                    <strong style={{ color: 'var(--text-main)', fontSize: '14.5px' }}>Giá trị cốt lõi:</strong> Sáng tạo đột phá, Học sinh là trung tâm, Lấy uy tín giảng dạy và chất lượng đầu ra làm kim chỉ nam.
                  </div>
                  <div style={{ borderLeft: '4px solid var(--accent-green)', paddingLeft: '16px', background: 'var(--bg-card)', padding: '14px 16px', borderRadius: '0 12px 12px 0', border: '1px solid var(--border)', borderLeftWidth: '4px' }}>
                    <strong style={{ color: 'var(--text-main)', fontSize: '14.5px' }}>Đối tác sư phạm:</strong> Liên kết chặt chẽ với tổ chức khảo thí quốc tế và đội ngũ giảng viên chuyên sâu từ các trường chuyên danh tiếng (Amsterdam, Chuyên Sư Phạm).
                  </div>
                </div>

                <button 
                  className="lp-btn lp-btn--accent lp-btn--full lp-btn--lg" 
                  style={{ marginTop: '36px' }}
                  onClick={() => { if (currentUser) { onBackToDashboard('forum'); } else { onNavigateToAuth('signup'); } }}
                >
                  {currentUser ? "Tham gia diễn đàn thảo luận ngay 🚀" : "Khám phá cộng đồng học tập EduPath"}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* ================= 5. PRICING DEDICATED PAGE ================= */}
        {activeLandingView === 'pricing' && (
          <div className="lp-container" style={{ padding: '40px 28px 80px' }}>
            <button 
              onClick={() => setActiveLandingView('home')}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--primary, #6c5ce7)',
                fontWeight: 'bold',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                fontSize: '14.5px',
                marginBottom: '28px',
                padding: 0
              }}
            >
              ← Quay lại trang chủ
            </button>

            <div className="lp-modal-grid">
              <div className="lp-modal-img-col" style={{ backgroundImage: `url(${studentSuccessImg})`, minHeight: '450px', borderRadius: '16px', overflow: 'hidden' }}>
                <div className="lp-modal-img-overlay">
                  <span className="lp-modal-badge" style={{ background: '#f59e0b' }}>🥇 Cam Kết Đạt Điểm Số</span>
                  <h3>Cam Kết Hoàn Học Phí Nếu Không Đạt Mục Tiêu</h3>
                </div>
              </div>
              <div className="lp-modal-info-col" style={{ padding: '0 10px' }}>
                <span className="lp-eyebrow">HỌC PHÍ TỐI ƯU</span>
                <h2 style={{ fontSize: '32px', fontWeight: '900', color: 'var(--lp-dark)', margin: '10px 0 18px 0' }}>Đầu tư thông minh cho tương lai đại học</h2>
                <p style={{ fontSize: '14.5px', lineHeight: '1.7', color: 'var(--text-secondary)' }}>Tiết kiệm tối đa chi phí đi học thêm cồng kềnh. Mở khóa toàn bộ đặc quyền Premium Pro chỉ với mức học phí ưu đãi trọn gói hợp lý nhất.</p>
                
                <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '24px', fontSize: '13.5px' }}>
                  <thead>
                    <tr style={{ borderBottom: '2px solid var(--border)', textAlign: 'left' }}>
                      <th style={{ padding: '10px 0', fontWeight: 'bold', fontSize: '14px' }}>Đặc quyền gói Premium Pro</th>
                      <th style={{ padding: '10px 0', fontWeight: 'bold', color: 'var(--primary)', fontSize: '14px' }}>Trọn đời</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr style={{ borderBottom: '1px solid var(--border)' }}>
                      <td style={{ padding: '10px 0', color: 'var(--text-secondary)' }}>Kho 1,200+ đề thi & video lý thuyết bám sát cấu trúc</td>
                      <td style={{ padding: '10px 0', color: 'var(--accent-green)', fontWeight: 'bold' }}>✓ Mở khóa toàn bộ</td>
                    </tr>
                    <tr style={{ borderBottom: '1px solid var(--border)' }}>
                      <td style={{ padding: '10px 0', color: 'var(--text-secondary)' }}>Hệ thống Adaptive AI sửa sai & chẩn đoán điểm yếu</td>
                      <td style={{ padding: '10px 0', color: 'var(--accent-green)', fontWeight: 'bold' }}>✓ Không giới hạn</td>
                    </tr>
                    <tr style={{ borderBottom: '1px solid var(--border)' }}>
                      <td style={{ padding: '10px 0', color: 'var(--text-secondary)' }}>Hỏi đáp EduBot AI 24/7 tức thời lời giải chi tiết</td>
                      <td style={{ padding: '10px 0', color: 'var(--accent-green)', fontWeight: 'bold' }}>✓ Vô hạn lượt</td>
                    </tr>
                    <tr style={{ borderBottom: '1px solid var(--border)' }}>
                      <td style={{ padding: '10px 0', color: 'var(--text-secondary)' }}>Hỗ trợ trực tiếp từ giáo viên chủ nhiệm môn học</td>
                      <td style={{ padding: '10px 0', color: 'var(--accent-green)', fontWeight: 'bold' }}>✓ Đặc quyền Pro</td>
                    </tr>
                  </tbody>
                </table>

                <div style={{ marginTop: '32px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'var(--bg-main, #f8fafc)', padding: '18px 24px', borderRadius: '16px', border: '1px solid var(--border)' }}>
                  <div>
                    <span style={{ fontSize: '11px', color: 'var(--text-muted)', display: 'block', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Học phí trọn gói cam kết:</span>
                    <div style={{ fontSize: '26px', fontWeight: '900', color: 'var(--accent-orange)', marginTop: '4px' }}>599.000đ <span style={{ fontSize: '13px', fontWeight: 'normal', color: 'var(--text-muted)' }}>/ trọn đời</span></div>
                  </div>
                  <button 
                    className="lp-btn lp-btn--accent lp-btn--lg" 
                    onClick={() => { if (currentUser) { onBackToDashboard('courses'); } else { onNavigateToAuth('signup'); } }}
                  >
                    {currentUser ? "Mua khóa học ngay ⚡" : "Nâng cấp Premium Pro"}
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ================= 6. FORUM DEDICATED PAGE ================= */}
        {activeLandingView === 'forum' && (
          <div className="lp-container" style={{ padding: '40px 28px 80px' }}>
            <button 
              onClick={() => setActiveLandingView('home')}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--primary, #6c5ce7)',
                fontWeight: 'bold',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                fontSize: '14.5px',
                marginBottom: '28px',
                padding: 0
              }}
            >
              ← Quay lại trang chủ
            </button>

            <Forum
              forumPosts={forumPosts}
              onAddPost={handleAddPostPublic}
              onLikePost={handleLikePostPublic}
              onAddComment={handleAddCommentPublic}
              currentUser={currentUser}
            />
          </div>
        )}

      </div>

      {/* ── FOOTER ── */}
      <footer className="lp-footer">
        <div className="lp-container">
          <div className="lp-footer__grid">
            <div className="lp-footer__brand">
              <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 }}>
                <div className="lp-logo-box" style={{ width: 36, height: 36, fontSize: 18 }}>E</div>
                <span style={{ fontWeight: 800, fontSize: 17, color: '#fff' }}>EduPath AI</span>
              </div>
              <p>Nền tảng luyện thi THPTQG thích ứng AI — học thông minh, đạt điểm cao.</p>
            </div>
            <div className="lp-footer__col">
              <h4>Môn học</h4>
              <a href="#subjects" onClick={(e) => { e.preventDefault(); setActiveLandingView('subjects'); }}>Toán Học</a>
              <a href="#subjects" onClick={(e) => { e.preventDefault(); setActiveLandingView('subjects'); }}>Vật Lý</a>
              <a href="#subjects" onClick={(e) => { e.preventDefault(); setActiveLandingView('subjects'); }}>Tiếng Anh</a>
              <a href="#subjects" onClick={(e) => { e.preventDefault(); setActiveLandingView('subjects'); }}>Hóa Học</a>
            </div>
            <div className="lp-footer__col">
              <h4>Sản phẩm</h4>
              <a href="#features" onClick={(e) => { e.preventDefault(); setActiveLandingView('features'); }}>Tính năng</a>
              <a href="#forum" onClick={(e) => { e.preventDefault(); setActiveLandingView('forum'); }}>Diễn đàn</a>
              <a href="#pricing" onClick={(e) => { e.preventDefault(); setActiveLandingView('pricing'); }}>Học phí</a>
              <a href="#stats" onClick={(e) => { e.preventDefault(); setActiveLandingView('about'); }}>Về chúng tôi</a>
            </div>
            <div className="lp-footer__col">
              <h4>Hỗ trợ</h4>
              <a href="#">Trung tâm trợ giúp</a>
              <a href="#">Liên hệ</a>
              <a href="#">Chính sách bảo mật</a>
            </div>
          </div>
          <div className="lp-footer__bottom">
            <span>© 2026 EduPath AI. Bản quyền thuộc về EduPath.</span>
            <span>Nhóm SWP391 NHOM1</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
